
project_id = "icwusduvaohosrvxlahh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54324
secure_channels = false

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
file_size_limit = "50MiB"
bucket_limit = 100
object_limit = 1000
connection_limit = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_functions]
enabled = true
port = 54321

[functions.create-checkout-session]

[functions.create-portal-session]

[functions.news-synthesis]

[functions.news-qa]

[functions.text-to-speech]

[functions.trending-topics]

[functions.stripe-webhook]
verify_jwt = false

[functions.subscription-success]

[functions.generate-debate]
