// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icwusduvaohosrvxlahh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imljd3VzZHV2YW9ob3NydnhsYWhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDg4MzcsImV4cCI6MjA2NjYyNDgzN30.v69fM_Wfa7bZ-lVCUVpd3oEL1E15bvuQdHgBtgn2dVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);